### ISSUE TITLE
FURB108 false positive with and

### ISSUE THREAD

**Issue by shaolo1** [dosisod/refurb#52] opened 2022-10-06 13:55 UTC
from enum import Enum

class FooBarBaz(Enum):
    FOO = 1
    BAR = 2
    BAZ = 3

def foo(bar: FooBarBaz, baz: bool):
    return bar == FooBarBaz.FOO or (bar == FooBarBaz.BAZ and baz)

refurb_test.py:11:12 [FURB108]: Use `x in (y, z)` instead of `x == y or x == z`

I don't see how in could be used in this case.

**Comment by henryiii** [comment] 2022-10-06 15:16
This is basically the problem mentioned in #46, I just didn't have a nice example.

**Comment by dosisod** [comment] 2022-10-06 19:23
Closing as duplicate of #46.

**Closed by dosisod** 2022-10-06 19:23 UTC
Labels: duplicate
